---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bralqeyr/public_html/
    - export THEMEPATH=/home/bralqeyr/public_html/wp-content/themes/bralim/
    - /bin/mkdir -p $THEMEPATH
    - /bin/cp -R wp-theme/bralim/. $THEMEPATH
